### ISSUE TITLE
Color coded graph lines

### ISSUE THREAD

**Issue by ShamsUlAzeem** [omegacen/conda-depgraph#2]
This is an awesome project!

I was thinking if maybe there can be a feature that can have color coded graph lines between connected graph nodes.

**Comment by teake** [comment]
Thanks!

`conda-depgraph` doesn't have any code to draw graphs. The ASCII graphs are rendered by the [asciinet library](https://github.com/cosminbasca/asciinet). So I'm afraid any feature request related to drawing the graphs should be posted there. I'm afraid I'll close this -- but thanks for the feedback!
