### ISSUE TITLE
conda package 1.2.0 is out-of-sync with source

### ISSUE THREAD

**Issue by stuarteberg** [omegacen/conda-depgraph#7]
There are two issues with the current conda package:

1. Commit ffdca9c8b2889f601074fc7b3f4fd5ac74685f7e bumped the conda package version, but didn't bump the version in [`__init__.py`][1].  That's not a huge deal, but potentially confusing.

[1]: https://github.com/omegacen/conda-depgraph/blob/master/src/conda_depgraph/__init__.py

2.  The changes from PR #5 are not present.  Was your local repo up-to-date when you built the package?

Here's what I see when I inspect the package manually:

```
$ wget -q https://anaconda.org/omegacen/conda-depgraph/1.2.0/download/noarch/conda-depgraph-1.2.0-0.tar.bz2
$ mkdir conda-depgraph-1.2.0-0
$ cd conda-depgraph-1.2.0-0
$ tar xjf ../conda-depgraph-1.2.0-0.tar.bz2

$ cat site-packages/conda_depgraph/__init__.py
__version__ = '1.1.1'

$ tail site-packages/conda_depgraph/conda_facade.py
def _package_datas_to_graph(datas):
    g = networkx.DiGraph()
    for data in datas:
        for p in data.values():
            n = p['name']
            g.add_node(n)
            for d in p.get('depends', []):
                o, *_ = d.split(' ')
                g.add_edge(n, o)
    return g
```

**Comment by teake** [comment]
Should be fixed now in 1.2.1. Thanks for reporting!
