### ISSUE TITLE
Group object has no attribute 'resultcallback'

### ISSUE THREAD

**Issue by meekrob** [omegacen/conda-depgraph#9]
It looks like this package isn't being maintained anymore, but I get this error with any invocation:

$ conda depgraph in mkl
Traceback (most recent call last):
  File "/Users/meekrob/miniconda3/bin/conda-depgraph", line 6, in <module>
    from conda_depgraph.cli import main
  File "/Users/meekrob/miniconda3/lib/python3.8/site-packages/conda_depgraph/cli.py", line 31, in <module>
    @main.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'

**Comment by teake** [comment]
Hi, can you post the output of the following two commands?

```
conda list --show-channel-urls
```

```
conda info
```

**Comment by meekrob** [comment]
Hi, thanks for the reply! I've attached the files with those commands run, although the output from the first command is quite extensive.

[conda_info.txt](https://github.com/omegacen/conda-depgraph/files/8764888/conda_info.txt)
[conda_list_channels.txt](https://github.com/omegacen/conda-depgraph/files/8764889/conda_list_channels.txt)

I wasn't able to make a smaller environment just for this:

conda create -n depgraph-test conda-depgraph -c omagacen
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: omagacen
  channel url: https://conda.anaconda.org/omagacen
  error code: 404

**Comment by teake** [comment]
Thanks for the output. Turns out click 8.1.0 has renamed a deprecated command. I'll release an updated version of conda-depgraph shortly. In the mean time, you could also install an older version of click:

```
conda install [...] click=7
```

Btw, you made a typo in the command above; it's `omegacen`, not `omagacen` :).

**Comment by teake** [comment]
I've pushed conda-depgraph 1.2.2 to the `omegacen` channel with the fix for the above issue.

**Comment by meekrob** [comment]
Thank you! It's working now. I will showcase it in a training about conda.
